#!/usr/bin/env python3
#define input
dna = 'GATGGGATTggggttttccccTCCCATGTGCTCAAGACTGGCGCTaaaaGttttGAGCTTCTCaaaaGTCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCggggACACTTTGCGTTCGGGCTGGGAGCGTGCTTTCCACGACGGTGACACGCTTCCCTGGATTGGCAGCCAGACTGCCTTCCGGGTCACTGCCATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGccccCTCTGAGTCAGGAAACAttttCAGACCTATGGAAACTACTTCCTGaaaaCAACGTTCTGTccccCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTccccGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATTCGCCAGAGGCTGCTccccCCGTGGccccTGCACCAGCAGCTCCTACACCGGCGGccccTGCACCAGccccCTCCTGGccccTGTCATCTTCTGTCCCTTCCCAGaaaaCCTACCAGGGCAGCTACGGTTTCCGTCTGGGCTTCTTGCATTCTGGGACAGCCAAGTCTGTGACTTGCACGTACTccccTGCCCTCAACAAGATGttttGCCAACTGGCCAAGACCTGCCCTGTGCAGCTGTGGGTTGATTCCACAccccCGCCCGGCACCCGCGTCCGCGCCATGGCCATCTACAAGCAGTCACAGCACATGACGGAGGTTGTGAGGCGCTGccccCACCATGAGCGCT'
#make uppercase
upper_dna = dna.upper()
#translate into complement
makecomplement = upper_dna.maketrans({'A':'T', 'T':'A', 'G':'C','C':'G'})
complement = upper_dna.translate(makecomplement)
#reverse
reverse_complement = complement[::-1]
print(reverse_complement)

#original capitalization
dna1 = 'ggCCaa'
makecomplement1 = dna1.maketrans({'A':'T', 'T':'A', 'G':'C','C':'G', 'g':'c', 'c':'g', 'a':'t', 't':'a'})
complement1 = dna1.translate(makecomplement1)
#reverse
reverse_complement1 = complement1[::-1]
print(reverse_complement1)